// Generated file. Do not edit.
// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PLUGIN_NAME = 'untitled';
  static const String PLUGIN_VERSION = '1.0.0+1';
  static const String AFRIKAANS_FAL_P1_MAY_JUNE_2023_MG = 'assets/pdfs/afrikaans/Afrikaans FAL P1 May-June 2023 MG.pdf';
  static const String AFRIKAANS_FAL_P1_MAY_JUNE_2023 = 'assets/pdfs/afrikaans/Afrikaans FAL P1 May-June 2023.pdf';
  static const String AFRIKAANS_FAL_P2_MAY_JUNE_2023_MG = 'assets/pdfs/afrikaans/Afrikaans FAL P2 May-June 2023 MG.pdf';
  static const String AFRIKAANS_FAL_P2_MAY_JUNE_2023 = 'assets/pdfs/afrikaans/Afrikaans FAL P2 May-June 2023.pdf';
  static const String AFRIKAANS_FAL_P3_MAY_JUNE_2023_MG = 'assets/pdfs/afrikaans/Afrikaans FAL P3 May-June 2023 MG.pdf';
  static const String AFRIKAANS_FAL_P3_MAY_JUNE_2023 = 'assets/pdfs/afrikaans/Afrikaans FAL P3 May-June 2023.pdf';
  static const String AFRIKAANS_HL_P1_MAY_JUNE_2023_MG = 'assets/pdfs/afrikaans/Afrikaans HL P1 May-June 2023 MG.pdf';
  static const String AFRIKAANS_HL_P1_MAY_JUNE_2023 = 'assets/pdfs/afrikaans/Afrikaans HL P1 May-June 2023.pdf';
  static const String AFRIKAANS_HL_P2_MAY_JUNE_2023_MG = 'assets/pdfs/afrikaans/Afrikaans HL P2 May-June 2023 MG.pdf';
  static const String AFRIKAANS_HL_P2_MAY_JUNE_2023 = 'assets/pdfs/afrikaans/Afrikaans HL P2 May-June 2023.pdf';
  static const String AFRIKAANS_HL_P3_MAY_JUNE_2023_MG = 'assets/pdfs/afrikaans/Afrikaans HL P3 May-June 2023 MG.pdf';
  static const String AFRIKAANS_HL_P3_MAY_JUNE_2023 = 'assets/pdfs/afrikaans/Afrikaans HL P3 May-June 2023.pdf';
  static const String ENGLISH_FAL_P1_MAY_JUNE_2023_MG = 'assets/pdfs/english/English FAL P1 May-June 2023 MG.pdf';
  static const String ENGLISH_FAL_P1_MAY_JUNE_2023 = 'assets/pdfs/english/English FAL P1 May-June 2023.pdf';
  static const String ENGLISH_FAL_P2_MAY_JUNE_2023_MG = 'assets/pdfs/english/English FAL P2 May-June 2023 MG.pdf';
  static const String ENGLISH_FAL_P2_MAY_JUNE_2023 = 'assets/pdfs/english/English FAL P2 May-June 2023.pdf';
  static const String ENGLISH_FAL_P3_MAY_JUNE_2023_MG = 'assets/pdfs/english/English FAL P3 May-June 2023 MG.pdf';
  static const String ENGLISH_FAL_P3_MAY_JUNE_2023 = 'assets/pdfs/english/English FAL P3 May-June 2023.pdf';
  static const String ENGLISH_HL_P1_MAY_JUNE_2023_MG = 'assets/pdfs/english/English HL P1 May-June 2023 MG.pdf';
  static const String ENGLISH_HL_P1_MAY_JUNE_2023 = 'assets/pdfs/english/English HL P1 May-June 2023.pdf';
  static const String ENGLISH_HL_P2_MAY_JUNE_2023_MG = 'assets/pdfs/english/English HL P2 May-June 2023 MG.pdf';
  static const String ENGLISH_HL_P2_MAY_JUNE_2023 = 'assets/pdfs/english/English HL P2 May-June 2023.pdf';
  static const String ENGLISH_HL_P3_MAY_JUNE_2023_MG = 'assets/pdfs/english/English HL P3 May-June 2023 MG.pdf';
  static const String ENGLISH_HL_P3_MAY_JUNE_2023 = 'assets/pdfs/english/English HL P3 May-June 2023.pdf';
  static const String MATHEMATICS_P1_MAY_JUNE_2023_MG_AFR_

  &

  _ENG

  =

  '

  assets/pdfs/maths/Mathematics P1 May-June 2023 MG Afr & Eng.pdf

  ';

  static const String MATHEMATICS_P1_NOV_2023_ENG = 'assets/pdfs/maths/Mathematics P1 Nov 2023 Eng.pdf';
  static const String MATHEMATICS_P2_MAY_JUNE_2023_MG_AFR_

  &

  _ENG

  =

  '

  assets/pdfs/maths/Mathematics P2 May-June 2023 MG Afr & Eng.pdf

  ';

  static const String MATHEMATICS_P2_NOV_2023_ADDENDUM_AFR_

  &

  _ENG

  =

  '

  assets/pdfs/maths/Mathematics P2 Nov 2023 Addendum Afr & Eng.pdf

  ';

  static const String MATHEMATICS_P2_NOV_2023_ENG = 'assets/pdfs/maths/Mathematics P2 Nov 2023 Eng.pdf';
  static const String PHYSICAL_SCIENCES_P1_MAY_JUNE_2023_ENG = 'assets/pdfs/science/Physical Sciences P1 May-June 2023 Eng.pdf';
  static const String PHYSICAL_SCIENCES_P1_MAY_JUNE_2023_MG_ENG_

  &

  _AFR

  =

  '

  assets/pdfs/science/Physical Sciences P1 May-June 2023 MG Eng & Afr.pdf

  ';

  static const String PHYSICAL_SCIENCES_P2_MAY_JUNE_2023_ENG = 'assets/pdfs/science/Physical Sciences P2 May-June 2023 Eng.pdf';
  static const String PHYSICAL_SCIENCES_P2_MAY_JUNE_2023_MG_ENG_

  &

  _AFR

  =

  '

  assets/pdfs/science/Physical Sciences P2 May-June 2023 MG Eng & Afr.pdf

  ';
}
